// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odev_BP;

#nullable disable

namespace Odev_BP.Migrations
{
    [DbContext(typeof(OtelDbContext))]
    [Migration("20240402035307_Spedatox")]
    partial class Spedatox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("Odev_BP.Models.calisan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yetki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Calisan");
                });

            modelBuilder.Entity("Odev_BP.Models.musteri", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdaID")
                        .HasColumnType("int");

                    b.Property<string>("RezDurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriID");

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("Odev_BP.Models.odeme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("OdemeMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RezervasyonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RezervasyonID");

                    b.ToTable("Odeme");
                });

            modelBuilder.Entity("Odev_BP.Models.otelOda", b =>
                {
                    b.Property<int>("OdaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdaID"));

                    b.Property<decimal>("Kapasite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdaDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OdaFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdaTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OdaID");

                    b.ToTable("OtelOda");
                });

            modelBuilder.Entity("Odev_BP.Models.rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervasyonID"));

                    b.Property<DateTime>("CheckinTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckoutTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MusteriID")
                        .HasColumnType("int");

                    b.Property<int>("OdaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RezervasyonTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RezervasyonID");

                    b.HasIndex("MusteriID");

                    b.HasIndex("OdaID");

                    b.ToTable("Rezervasyon");
                });

            modelBuilder.Entity("Odev_BP.Models.odeme", b =>
                {
                    b.HasOne("Odev_BP.Models.rezervasyon", "Rezervasyon")
                        .WithMany("Odemeler")
                        .HasForeignKey("RezervasyonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("Odev_BP.Models.rezervasyon", b =>
                {
                    b.HasOne("Odev_BP.Models.musteri", "Musteri")
                        .WithMany("Rezervasyon")
                        .HasForeignKey("MusteriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odev_BP.Models.otelOda", "OtelOda")
                        .WithMany("Rezervasyon")
                        .HasForeignKey("OdaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("OtelOda");
                });

            modelBuilder.Entity("Odev_BP.Models.musteri", b =>
                {
                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("Odev_BP.Models.otelOda", b =>
                {
                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("Odev_BP.Models.rezervasyon", b =>
                {
                    b.Navigation("Odemeler");
                });
#pragma warning restore 612, 618
        }
    }
}
